[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_chromadb"
description = "Chroma Vector Index integration for Ordeq"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Nilay Karahan Afacan" },
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.4.0",
    "chromadb",
]

[tool.ordeq-dev]
group = "ios"
logo_url = "https://home-wordpress.deeplearning.ai/wp-content/uploads/2023/12/chroma_logotype.png"

[dependency-groups]
test = []

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_chromadb/_version.py"
tag_regex = "^ordeq-chromadb/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-chromadb/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.coverage.run]
omit = [
    "src/ordeq_chromadb/_version.py"
]
