services:
  airflow-standalone:
    image: apache/airflow:slim-3.1.4rc1-python3.13
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./db:/opt/airflow
    command: >
      bash -c "airflow standalone"
