[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ordeq_iceberg"
description = "Iceberg integration for Ordeq"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Jose R. Sanchez Viloria <@josersanvil>" },
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
maintainers = [
    { name = "Niels Neerhoff" },
    { name = "Simon Brugman" },
]
requires-python = ">=3.10"
dependencies = [
    "ordeq>=1.3.3",
    "pyarrow>=21.0.0",
    "pyiceberg[sql-sqlite]>=0.10.0",
]

[tool.ordeq-dev]
group = "ios"
logo_url = "https://iceberg.apache.org/assets/images/Iceberg-logo.svg"

[dependency-groups]
test = [
    "ordeq-common",
    "ordeq-test-utils",
    "ordeq-dev-tools",
    "pytest",
]

[tool.setuptools_scm]
root = "../../"
version_file = "src/ordeq_iceberg/_version.py"
tag_regex = "^ordeq-iceberg/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match ordeq-iceberg/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.coverage.run]
omit = ["src/ordeq_iceberg/_version.py"]
